### ISSUE TITLE
recolor causes a segfault

### ISSUE THREAD

**Issue by sc0ttbeardsley** [yahoo/zeus#16]
<pre>
./zeus conf/01.namespaces.yaml conf/02.types.yaml conf/03.dimensions.yaml conf/04.master.yaml conf/05.settings.yaml --cpp-code > output/configuration.cc
content "gray" did not match regular expression "recolor"
zeus: parser.cc:204: void parser::Parser::processValue(const YAML::Node&, const parser::Parser::Result&, Value&) const: Assertion `false' failed.
Aborted (core dumped)
make: *** [output/configuration.cc] Error 134
</pre>

**Comment by sc0ttbeardsley** [comment]
Seems like the problem is limited to ubuntu 14.04... it works fine on OS X.

**Comment by dmorilha-yahoo** [comment]
I will try to reproduce on my arch linux...

**Comment by dmorilha-yahoo** [comment]
This is actually correct. It currently `assert(false)` for exiting. I think eventually that needs to be replaced to some more graceful exit technique.
