### ISSUE TITLE
Defect: incorrect switch hierarchy for 4th context

### ISSUE THREAD

**Issue by sc0ttbeardsley** [yahoo/zeus#18]
The following config doesn't work as expected... I expect this context:
- environment: production
- role: proxy
- pop: EX02
- bucket: 3

to return this list for the hosts value:
- EX02-PROXY13
- EX02-PROXY15

But instead it returns an empty list. Here is the config:

<pre>
$ for i in *;do echo \# $i;cat $i;done
#01.namespaces.yaml

---
- namespaces:
  - config
#02.dimensions.yaml

---
- dimensions:
  - environment
  - role
  - bucket
  - pop
#03.master.yaml

---
- settings: master

  hosts:
    - !!ignore
#04.pop.ex01.yaml

---
- settings:
    role: proxy
    environment: production
    pop: EX01
    bucket: 1

  hosts:
    - EX01-PROXY03
    - EX01-PROXY04

- settings:
    role: proxy
    environment: production
    pop: EX01
    bucket: 2

  hosts:
    - EX01-PROXY01
    - EX01-PROXY02
    - EX01-PROXY26
    - EX01-PROXY27

- settings:
    role: proxy
    environment: production
    pop: EX01
    bucket: 3

  hosts:
    - EX01-PROXY23
    - EX01-PROXY24
#04.pop.ex02.yaml

---
- settings:
    role: proxy
    environment: production
    pop: EX02
    bucket: 1

  hosts:
    - EX02-PROXY14
    - EX02-PROXY16

- settings:
    role: proxy
    environment: production
    pop: EX02
    bucket: 2

  hosts:
    - EX02-PROXY10
    - EX02-PROXY12

- settings:
    role: proxy
    environment: production
    pop: EX02
    bucket: 3

  hosts:
    - EX02-PROXY13
    - EX02-PROXY15
</pre>

I'll attach the generated code...

[list-flatten-4dims.txt](https://github.com/yahoo/zeus/files/512999/list-flatten-4dims.txt)

**Comment by sc0ttbeardsley** [comment]
This section seems wrong:

<pre>
          switch (this.bucket) {
          case 1:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY03");
              value.push("EX01-PROXY04");
              break;
            }
            break;
          case 2:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY01");
              value.push("EX01-PROXY02");
              value.push("EX01-PROXY26");
              value.push("EX01-PROXY27");
              break;
            }
            break;
          case 3:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY23");
              value.push("EX01-PROXY24");
              break;
            }
            break;
          case 1:
            switch (this.pop) {
            case 2:
              value.push("EX02-PROXY14");
              value.push("EX02-PROXY16");
              break;
            }
            break;
          case 2:
            switch (this.pop) {
            case 2:
              value.push("EX02-PROXY10");
              value.push("EX02-PROXY12");
              break;
            }
            break;
          case 3:
            switch (this.pop) {
            case 2:
              value.push("EX02-PROXY13");
              value.push("EX02-PROXY15");
              break;
            }
            break;
          }
</pre>

Notice there are duplicate cases for bucket=1, bucket=2, bucket=3 respectively

**Comment by sc0ttbeardsley** [comment]
Looks like it isn't language-specific (i see the same problem in php). Here is what it should be generating (for js):

<pre>
          switch (this.bucket) {
          case 1:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY03");
              value.push("EX01-PROXY04");
              break;
            case 2:
              value.push("EX02-PROXY14");
              value.push("EX02-PROXY16");
              break;
            }
            break;
          case 2:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY01");
              value.push("EX01-PROXY02");
              value.push("EX01-PROXY26");
              value.push("EX01-PROXY27");
              break;
            case 2:
              value.push("EX02-PROXY10");
              value.push("EX02-PROXY12");
              break;
            }
            break;
          case 3:
            switch (this.pop) {
            case 1:
              value.push("EX01-PROXY23");
              value.push("EX01-PROXY24");
              break;
            case 2:
              value.push("EX02-PROXY13");
              value.push("EX02-PROXY15");
              break;
            }
            break;
          }
</pre>

**Comment by dmorilha-yahoo** [comment]
The problem here was that leaf nodes were not getting ordered during graph sorting.
